name: build-linux64

on:
  push:
    paths-ignore:
    - '**/README.md'
  pull_request:
    paths-ignore:
    - '**/README.md'
jobs:

  build-linux64:
    runs-on: ubuntu-18.04
    strategy:
        matrix:
          cfg:
          - {target: linux, opt: gcc6}
    env:
     TARGET: ${{matrix.cfg.target}}
     OPT: ${{matrix.cfg.opt}}
    steps:
    - uses: actions/checkout@v2
    - name: Scripts Calc Formula - ${{matrix.cfg.target}} - ${{matrix.cfg.opt}}
      run: ./scripts/calculate_formulas.sh
    - name: Scripts Install
      run: ./scripts/$TARGET/install.sh
    - name: build
      run: ./scripts/build.sh
      env:
        GA_CI_SECRET: ${{ secrets.CI_SECRET }}

  deploy:
    runs-on: ubuntu-18.04
    needs: build-linux64
    if: ${{ github.head_ref || github.ref_name }} == 'ci-releases-test'
    steps:
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          name: nightly builds
          gzip: false
          allow_override: true
          files: >
            /home/runner/work/apothecary/apothecary/*
          
    
