name: build-vs2022-arm64

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'
    
jobs:

  build-vs2022:
    runs-on: windows-2022
    strategy:
      matrix:
        bundle: [1,2,3,4]
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Setup msys2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          unzip
          dos2unix
          gperf
          git
          python3
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gcc-libs
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gdb
          mingw-w64-x86_64-make
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Determine Release
      id: vars
      shell: bash
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          echo "release=nightly" >> $GITHUB_ENV
          echo "prerelease=false" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == "refs/heads/bleeding" ]]; then
          echo "release=bleeding" >> $GITHUB_ENV
          echo "prerelease=true" >> $GITHUB_ENV
        fi
    - name: BuildARM64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: scripts/build.sh
      env:
        BUNDLE: ${{ matrix.bundle }}
        TARGET: "vs"
        ARCH: arm64
        VS_VER: 17
        GA_CI_SECRET: ${{ secrets.CI_SECRET }}
    - name: Package
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: scripts/package.sh
      env:
        BUNDLE: ${{ matrix.bundle }}
        TARGET: "vs"
        ARCH: arm64
        VS_VER: 17
        GA_CI_SECRET: ${{ secrets.CI_SECRET }}
    - name: Update Release ARM64
      if: (github.repository == 'openframeworks/apothecary' && github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/bleeding'))
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.release }}
        release: ${{ env.release }}
        prerelease: ${{ env.prerelease }}
        files: out/openFrameworksLibs_${{ env.release }}_vs_arm64_${{ matrix.bundle }}.zip

